//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCLogin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adattipus
    {
        public int ID { get; set; }
        public string Szakok { get; set; }
        public string TanarCim { get; set; }
        public string SzakAllapot { get; set; }
        public string Tanszek { get; set; }
        public string TanariAllas { get; set; }
        public string ISBN_tananyag { get; set; }
        public string Formatum { get; set; }
        public string Aktivitas { get; set; }
        public string Granturi { get; set; }
        public string Rendezvenyek { get; set; }
        public string Manifestari { get; set; }
        public string Graduri_de_promovare { get; set; }
        public string Programe_de_studii { get; set; }
        public string Gradul_de_multumire { get; set; }
        public string TanarNev { get; set; }
    }
}
